name: 构建cpu容器

on:
  push:
    paths:
      - 'cpu-dockerfile' # Monitor changes in the specified Dockerfile path

permissions:
  contents: write

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push qubic-CPU image for ARM
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./cpu-dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qubic-cpu:latest
          platforms: linux/arm64, linux/arm/v7  # Specify ARM architectures
